from typing import Any
from typing import ClassVar
from typing import Dict
from typing import List
from typing import Tuple

__version__: str


class Booking:
    STRICT: ClassVar["Booking"]
    STRICT_WITH_SIZE: ClassVar["Booking"]
    NONE: ClassVar["Booking"]
    AVERAGE: ClassVar["Booking"]
    FIFO: ClassVar["Booking"]
    LIFO: ClassVar["Booking"]
    HIFO: ClassVar["Booking"]

    def __init__(self, value: Any) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __str__(self) -> str: ...


class ParserError:
    source: Any
    message: str
    entry: Any

    def __init__(self, source: Any, message: str, entry: Any = None) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...


def load_file(filename: str) -> Tuple[List[Any], List[Any], Dict[str, Any]]: ...
def parse_string(
    content: str, filename: str | None = ...
) -> Tuple[List[Any], List[Any], Dict[str, Any]]: ...
def check_file_rust(filename: str) -> Tuple[int, int, int, int]: ...
def load_file_and_book(filename: str) -> Tuple[List[Any], List[Any], Dict[str, Any]]: ...
def load_string_and_book(
    content: str, filename: str = ...
) -> Tuple[List[Any], List[Any], Dict[str, Any]]: ...
