from typing import Any
from typing import Dict
from typing import List
from typing import Tuple

__version__: str

__all__ = [
    "__version__",
    "build_options_map",
    "check_file_rust",
    "load_file",
    "parse_string",
]

def load_file(filename: str) -> Tuple[List[Any], List[Any], Dict[str, Any]]: ...
def parse_string(
    content: str, filename: str | None = ...
) -> Tuple[List[Any], List[Any], Dict[str, Any]]: ...
def check_file_rust(filename: str) -> Tuple[int, int, int, int]: ...
def load_file_and_book(filename: str) -> Tuple[List[Any], List[Any], Dict[str, Any]]: ...
def load_string_and_book(
    content: str, filename: str = ...
) -> Tuple[List[Any], List[Any], Dict[str, Any]]: ...
def build_options_map(filename: str | None = ...) -> Dict[str, Any]: ...
