name: upload-wheel

on:
  push:
    tags:
      - "2.*"

jobs:
  maxos-and-windows:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        python: ['3.5', '3.6', '3.7', '3.8']
        os: [windows, macos]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - run: pip install wheel twine

      - run: python setup.py build_ext --compiler=msvc --define YY_NO_UNISTD_H
        if: startsWith(runner.os, 'Windows')

      - run: python setup.py bdist_wheel

      - run: twine upload dist/*
        env:
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
          TWINE_USERNAME: __token__


  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: RalfG/python-wheels-manylinux-build@v0.3.1
        with:
          python-versions: 'cp35-cp35m cp36-cp36m cp37-cp37m cp38-cp38'

      - run: ls dist -ahl
      - uses: actions/setup-python@v2
      - run: pip install twine
      - run: twine upload dist/*manylinux*
        env:
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
          TWINE_USERNAME: __token__